# Generated by Django 6.0.1 on 2026-02-01 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_studentprofile_teacherprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='preferred_language',
            field=models.CharField(blank=True, help_text='Preferred language for learning', max_length=50),
        ),
    ]
